# "name": [id, owner, troops]
territories = {
    # NORTH AMERICA
    "ALASKA": [1],
    "NORTHWEST_TERRITORY": [2],
    "GREENLAND": [3],
    "ALBERTA": [4],
    "ONTARIO": [5],
    "QUEBEC": [6],
    "WESTERN_UNITED_STATES": [7],
    "EASTERN_UNITED_STATES": [8],
    "CENTRAL_AMERICA": [9],
    "HAWAII": [10],  #
    # SOUTH AMERICA,
    "VENEZUELA": [11],
    "PERU": [12],
    "BRAZIL": [13],
    "ARGENTINA": [14],
    "FALKLAND_ISLANDS": [15],  #
    # AFRICA,
    "NORTH_AFRICA": [16],
    "EGYPT": [17],
    "EAST_AFRICA": [18],
    "CONGO": [19],
    "SOUTH_AFRICA": [20],
    "MADAGASCAR": [21],
    # EUROPE,
    "ICELAND": [22],
    "SVALBARD": [23],  # ,
    "SCANDINAVIA": [24],
    "UKRAINE": [25],
    "GREAT_BRITAIN": [26],
    "NORTHERN_EUROPE": [27],
    "SOUTHERN_EUROPE": [28],
    "WESTERN_EUROPE": [29],
    # OCEANIA (AUSTRALIA),
    "INDONESIA": [30],
    "PHILLIPINES": [31],  # ,
    "NEW_GUINEA": [32],
    "WESTERN_AUSTRALIA": [33],
    "EASTERN_AUSTRALIA": [34],
    "NEW_ZEALAND": [35],  # ,
    # ASIA,
    "SIAM": [36],
    "INDIA": [37],
    "CHINA": [38],
    "MONGOLIA": [39],
    "JAPAN": [40],
    "IRKUTSK": [41],
    "YAKUTSK": [42],
    "KAMCHATKA": [43],
    "SIBERIA": [44],
    "AFGHANISTAN": [45],
    "URAL": [46],
    "MIDDLE_EAST": [47],
}
extra_territories = [
    "FALKLAND_ISLANDS",
    "NEW_ZEALAND",
    "PHILLIPINES",
    "HAWAII",
    "SVALBARD",
]
